String workerDir = 'inference-api'
String credentialsId = 'deploy-key-github'
String registryUrl = 'https://registry.easyrice.tech'
def remote = [:]

pipeline {
    agent any
     parameters {
    }
    stages {
        stage('Get env') {
            steps {
                sh 'echo "hello world"'
            }
        }
    //     stage('Prepare Resource To Host') {
    //             steps {
    //             script {
    //                 sshagent(['easyrice-ai-prod']) {
    //                     sh "ssh  -o StrictHostKeyChecking=no   ${params.USER}@${params.HOST} rm -rf deploy"
    //                     sh "ssh  -o StrictHostKeyChecking=no   ${params.USER}@${params.HOST} mkdir deploy"
    //                     sh "scp resources/.env ${params.USER}@${params.HOST}:deploy/.env"
    //                     sh "scp -r resources  ${params.USER}@${params.HOST}:deploy/resources"
    //             }       
    //             }
    //         }
    //     }
    //     stage('Update worker image') {
    //                 steps {
    //                 script {
    //                     sshagent(['easyrice-ai-prod']) {
    //                         sh "ssh  -o StrictHostKeyChecking=no   ${params.USER}@${params.HOST} docker-compose -f deploy/resources/docker-compose-worker.yml --env-file deploy/.env pull" }       
    //                 }
    //             }
    //     }
    //     stage('Deploy Worker') {
    //             steps {
    //             script {
    //                 sshagent(['easyrice-ai-prod']) {
    //                     sh "ssh  -o StrictHostKeyChecking=no  ${params.USER}@${params.HOST} docker-compose -f deploy/resources/docker-compose-worker.yml --env-file deploy/.env up -d"
    //             }       
    //             }
    //         }
    // }
    }
}